/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SimDatabaseRouteImport } from './routes/sim-database'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ProAccountsRouteImport } from './routes/pro-accounts'
import { Route as PayfastResultRouteImport } from './routes/payfast-result'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as LuckyDrawRouteImport } from './routes/lucky-draw'
import { Route as FakeWhatsappRouteImport } from './routes/fake-whatsapp'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminStoreRouteImport } from './routes/admin.store'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLuckyRouteImport } from './routes/admin.lucky'
import { Route as AdminHomeItemsRouteImport } from './routes/admin.home-items'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as ApiPublicSimRouteImport } from './routes/api/public/sim'
import { Route as ApiPublicPayfastCallbackRouteImport } from './routes/api/public/payfast-callback'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SimDatabaseRoute = SimDatabaseRouteImport.update({
  id: '/sim-database',
  path: '/sim-database',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAccountsRoute = ProAccountsRouteImport.update({
  id: '/pro-accounts',
  path: '/pro-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const PayfastResultRoute = PayfastResultRouteImport.update({
  id: '/payfast-result',
  path: '/payfast-result',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LuckyDrawRoute = LuckyDrawRouteImport.update({
  id: '/lucky-draw',
  path: '/lucky-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeWhatsappRoute = FakeWhatsappRouteImport.update({
  id: '/fake-whatsapp',
  path: '/fake-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLuckyRoute = AdminLuckyRouteImport.update({
  id: '/lucky',
  path: '/lucky',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeItemsRoute = AdminHomeItemsRouteImport.update({
  id: '/home-items',
  path: '/home-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSimRoute = ApiPublicSimRouteImport.update({
  id: '/api/public/sim',
  path: '/api/public/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayfastCallbackRoute =
  ApiPublicPayfastCallbackRouteImport.update({
    id: '/api/public/payfast-callback',
    path: '/api/public/payfast-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/fake-whatsapp': typeof FakeWhatsappRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/my-orders': typeof MyOrdersRoute
  '/order': typeof OrderRoute
  '/payfast-result': typeof PayfastResultRoute
  '/pro-accounts': typeof ProAccountsRoute
  '/receipt': typeof ReceiptRoute
  '/refer': typeof ReferRoute
  '/shop': typeof ShopRoute
  '/sim-database': typeof SimDatabaseRoute
  '/store': typeof StoreRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/home-items': typeof AdminHomeItemsRoute
  '/admin/lucky': typeof AdminLuckyRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast-callback': typeof ApiPublicPayfastCallbackRoute
  '/api/public/sim': typeof ApiPublicSimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/fake-whatsapp': typeof FakeWhatsappRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/my-orders': typeof MyOrdersRoute
  '/order': typeof OrderRoute
  '/payfast-result': typeof PayfastResultRoute
  '/pro-accounts': typeof ProAccountsRoute
  '/receipt': typeof ReceiptRoute
  '/refer': typeof ReferRoute
  '/shop': typeof ShopRoute
  '/sim-database': typeof SimDatabaseRoute
  '/store': typeof StoreRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/home-items': typeof AdminHomeItemsRoute
  '/admin/lucky': typeof AdminLuckyRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/payfast-callback': typeof ApiPublicPayfastCallbackRoute
  '/api/public/sim': typeof ApiPublicSimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/fake-whatsapp': typeof FakeWhatsappRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/my-orders': typeof MyOrdersRoute
  '/order': typeof OrderRoute
  '/payfast-result': typeof PayfastResultRoute
  '/pro-accounts': typeof ProAccountsRoute
  '/receipt': typeof ReceiptRoute
  '/refer': typeof ReferRoute
  '/shop': typeof ShopRoute
  '/sim-database': typeof SimDatabaseRoute
  '/store': typeof StoreRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/home-items': typeof AdminHomeItemsRoute
  '/admin/lucky': typeof AdminLuckyRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/store': typeof AdminStoreRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast-callback': typeof ApiPublicPayfastCallbackRoute
  '/api/public/sim': typeof ApiPublicSimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/fake-whatsapp'
    | '/lucky-draw'
    | '/my-orders'
    | '/order'
    | '/payfast-result'
    | '/pro-accounts'
    | '/receipt'
    | '/refer'
    | '/shop'
    | '/sim-database'
    | '/store'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/home-items'
    | '/admin/lucky'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/products/$slug'
    | '/store/$slug'
    | '/admin/'
    | '/api/public/payfast-callback'
    | '/api/public/sim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/fake-whatsapp'
    | '/lucky-draw'
    | '/my-orders'
    | '/order'
    | '/payfast-result'
    | '/pro-accounts'
    | '/receipt'
    | '/refer'
    | '/shop'
    | '/sim-database'
    | '/store'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/home-items'
    | '/admin/lucky'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/products/$slug'
    | '/store/$slug'
    | '/admin'
    | '/api/public/payfast-callback'
    | '/api/public/sim'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/fake-whatsapp'
    | '/lucky-draw'
    | '/my-orders'
    | '/order'
    | '/payfast-result'
    | '/pro-accounts'
    | '/receipt'
    | '/refer'
    | '/shop'
    | '/sim-database'
    | '/store'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/home-items'
    | '/admin/lucky'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/store'
    | '/products/$slug'
    | '/store/$slug'
    | '/admin/'
    | '/api/public/payfast-callback'
    | '/api/public/sim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FakeWhatsappRoute: typeof FakeWhatsappRoute
  LuckyDrawRoute: typeof LuckyDrawRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OrderRoute: typeof OrderRoute
  PayfastResultRoute: typeof PayfastResultRoute
  ProAccountsRoute: typeof ProAccountsRoute
  ReceiptRoute: typeof ReceiptRoute
  ReferRoute: typeof ReferRoute
  ShopRoute: typeof ShopRoute
  SimDatabaseRoute: typeof SimDatabaseRoute
  StoreRoute: typeof StoreRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicPayfastCallbackRoute: typeof ApiPublicPayfastCallbackRoute
  ApiPublicSimRoute: typeof ApiPublicSimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim-database': {
      id: '/sim-database'
      path: '/sim-database'
      fullPath: '/sim-database'
      preLoaderRoute: typeof SimDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-accounts': {
      id: '/pro-accounts'
      path: '/pro-accounts'
      fullPath: '/pro-accounts'
      preLoaderRoute: typeof ProAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payfast-result': {
      id: '/payfast-result'
      path: '/payfast-result'
      fullPath: '/payfast-result'
      preLoaderRoute: typeof PayfastResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucky-draw': {
      id: '/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/lucky-draw'
      preLoaderRoute: typeof LuckyDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-whatsapp': {
      id: '/fake-whatsapp'
      path: '/fake-whatsapp'
      fullPath: '/fake-whatsapp'
      preLoaderRoute: typeof FakeWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lucky': {
      id: '/admin/lucky'
      path: '/lucky'
      fullPath: '/admin/lucky'
      preLoaderRoute: typeof AdminLuckyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-items': {
      id: '/admin/home-items'
      path: '/home-items'
      fullPath: '/admin/home-items'
      preLoaderRoute: typeof AdminHomeItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sim': {
      id: '/api/public/sim'
      path: '/api/public/sim'
      fullPath: '/api/public/sim'
      preLoaderRoute: typeof ApiPublicSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payfast-callback': {
      id: '/api/public/payfast-callback'
      path: '/api/public/payfast-callback'
      fullPath: '/api/public/payfast-callback'
      preLoaderRoute: typeof ApiPublicPayfastCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHomeItemsRoute: typeof AdminHomeItemsRoute
  AdminLuckyRoute: typeof AdminLuckyRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHomeItemsRoute: AdminHomeItemsRoute,
  AdminLuckyRoute: AdminLuckyRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoreRouteChildren {
  StoreSlugRoute: typeof StoreSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSlugRoute: StoreSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FakeWhatsappRoute: FakeWhatsappRoute,
  LuckyDrawRoute: LuckyDrawRoute,
  MyOrdersRoute: MyOrdersRoute,
  OrderRoute: OrderRoute,
  PayfastResultRoute: PayfastResultRoute,
  ProAccountsRoute: ProAccountsRoute,
  ReceiptRoute: ReceiptRoute,
  ReferRoute: ReferRoute,
  ShopRoute: ShopRoute,
  SimDatabaseRoute: SimDatabaseRoute,
  StoreRoute: StoreRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicPayfastCallbackRoute: ApiPublicPayfastCallbackRoute,
  ApiPublicSimRoute: ApiPublicSimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
